export const services = [
  { slug: "voice-agents", name: "AI voice agents", line: "A good first impression. Even when you’re busy.", description: "Answer enquiries, capture the important details and route the next step while your team gets on with the job.", price: "Custom scope", priceNote: "tailored to your business", items: ["Enquiry capture and common questions", "Call routing and clear human hand-off", "Booking and CRM connections, scoped to your business"], detail: "We shape the conversation around your business, test the awkward questions and agree when a person needs to take over. Advanced integrations are quoted separately.", range: "Inclusions, minutes and call routing agreed before launch." },
  { slug: "business-automation", name: "Business automation", line: "The follow-up. The copy-paste. The thing you forgot.", description: "Connect the tools you already use so the same piece of information doesn’t need to be typed three times.", price: "Custom scope", priceNote: "agreed before we build", items: ["Lead capture, quote follow-up and reminders", "Documents, reporting and CRM updates", "Booking, scheduling and invoice workflows"], detail: "We map one real workflow, find the points that cause rework and build a clear route between your tools. You see what happened, what failed and what needs a human.", range: "Simple to complex workflows scoped and agreed before work begins." },
  { slug: "custom-assistants", name: "Custom AI assistants", line: "Your company knowledge. Ready when it’s needed.", description: "Help customers and staff find useful answers in the information your business already has.", price: "Custom scope", priceNote: "agreed before we build", items: ["Website and customer support assistants", "Internal knowledge and staff information", "Document questions with source references"], detail: "We work with your approved information, define who can access it and test how the assistant handles a question it cannot answer. More complex builds are scoped as integration projects.", range: "Document preparation, access requirements and integrations affect the final scope." },
  { slug: "ai-integration", name: "AI integration projects", line: "Make the pieces work together.", description: "Connect AI to your business software, with custom workflows and interfaces built around how your team actually works.", price: "Custom scope", priceNote: "agreed before we build", items: ["CRM, business software and API connections", "Custom interfaces and internal tools", "Agent workflows with clear oversight"], detail: "We define the data flow, access boundaries and review points before building. The work includes testing and a practical handover so the result is something your team can use and understand.", range: "Scope and deliverables agreed individually before starting." },
  { slug: "opportunity-audit", name: "AI opportunity audit", line: "Start with the problem. Then pick the technology.", description: "A practical look at where your time goes, what’s worth fixing and what you can safely leave alone.", price: "Fixed review", priceNote: "practical workflow review", items: ["Workflow review and recurring admin drains", "Missed lead and automation opportunities", "Priorities, estimated costs and potential return"], detail: "You leave with an ordered set of recommendations and a sensible first project. Estimated savings are planning assumptions to validate, not promised outcomes.", range: "Opportunity audit scope agreed before review. Any implementation is scoped separately." },
] as const;

export type Service = (typeof services)[number];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((service) => service.slug === slug);
}
